name: Pull Request

permissions:
  contents: read

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest', 'windows-11-arm']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
      name: Checkout
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0'
    - run: dotnet test

  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      name: Checkout
    - uses: actions/dependency-review-action@v4
      name: Dependency Review
      with:
        allow-licenses: MIT, Apache-2.0, BSD-2-Clause
        fail-on-scopes: development, runtime, unknown
